name: build-macos
on: 
  push:
  workflow_dispatch:
env:
  targetName: qmake_action
jobs:
  build:
    name: Build
    runs-on: macos-10.15
    strategy:
      matrix:
        #qt_ver: [5.9.9, 5.12.10, 5.15.2]
        qt_ver: [5.15.2]
        qt_arch: [clang_64]
    steps:
      - name: cacheQt
        id: MacosCacheQt
        uses: actions/cache@v1
        with:
          path: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
          key: ${{ runner.os }}-Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}   
      - name: Install Qt
        # if: steps.MacosCacheQt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2.10.0
        with:
          version: ${{ matrix.qt_ver }}
          cached: ${{ steps.MacosCacheQt.outputs.cache-hit }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          qmake
          make
          ls -l
      - name: Deploy app
        run: |
          macdeployqt ${{ env.targetName }}.app -dmg
          ls -l
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}
          path: ${{ env.targetName }}.dmg